{
 "title": "IOT Sensor Data",
 "time": { "from": "2025-01-04T04:36:27.000Z", "to": "2025-12-22T18:56:15.000Z" },
 "templating": {
  "list": [
   { "name": "latitude", "label": "Latitude", "query": "52.5" },
   { "name": "longitude", "label": "Longitude", "query": "13.5" },
   {
    "name": "region",
    "label": "Region",
    "query": "SELECT region_name FROM demo.german_regions WHERE region_name != 'Bremen' ORDER BY region_name;"
   },
   {
    "name": "search_categories",
    "label": "Search Categories",
    "query": "Tourism : tourism_info, Economics : economics, Invasive Species : introduced_species,  Transportation : transportation"
   },
   { "name": "keyword", "label": "Search Term", "query": "cars" },
   { "name": "town_name", "query": "Berlin" }
  ]
 },
 "panels": [
  { "title": "Text Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "'$keyword' relevance to '$search_categories'",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT region_name, _score FROM demo.german_regions WHERE MATCH($search_categories, '$keyword') ORDER By _score DESC limit 100;"
    }
   ]
  },
  {
   "title": "$search_categories and $region",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT $search_categories FROM demo.german_regions WHERE  region_name = '$region' ORDER By _score DESC limit 1;"
    }
   ]
  },
  { "title": "IOT Sensor Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Last Measurement Time",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "dataset": "docs",
     "rawSql": "SELECT MAX(d2.measurement_time) last_time FROM demo.climate_data d2 WHERE $__timeFilter(\"measurement_time\")"
    }
   ]
  },
  {
   "title": "Temperture",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  measurement_time as time,\n  min(data['temperature'] -273.15) as temperature_min,\n  max(data['temperature'] -273.15) as temperature_max\nFROM\n  demo.climate_data d\n      ,  \"demo\".\"german_regions\" r\nWHERE WITHIN(d.geo_location, r.geo_coords)\nAND (r.region_name = '${region}' OR 'ALL' =  '${region}')\nAND d.measurement_time = (SELECT MAX(d2.measurement_time) FROM demo.climate_data d2 WHERE $__timeFilter(\"measurement_time\"))\nGROUP BY measurement_time;\n"
    }
   ]
  },
  {
   "title": "Pressure (mbar)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  measurement_time as time,\n  min(data['pressure'] / 100) as pressure_min,\n  max(data['pressure'] / 100) as pressure_max\nFROM\n  demo.climate_data d\n      ,  \"demo\".\"german_regions\" r\nWHERE WITHIN(d.geo_location, r.geo_coords)\nAND (r.region_name = '${region}' OR 'ALL' =  '${region}')\nAND d.measurement_time = (SELECT MAX(d2.measurement_time) FROM demo.climate_data d2 WHERE $__timeFilter(\"measurement_time\"))\nGROUP BY measurement_time;\n"
    }
   ]
  },
  {
   "title": "Wind Speed (M/s)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  measurement_time as time,\n  min(sqrt(data['u10']*data['u10'] + data['v10']*data['v10'])) as wind_min,\n  max(sqrt(data['u10']*data['u10'] + data['v10']*data['v10'])) as wind_max\nFROM\n  demo.climate_data d\n      ,  \"demo\".\"german_regions\" r\nWHERE WITHIN(d.geo_location, r.geo_coords)\nAND (r.region_name = '${region}' OR 'ALL' =  '${region}')\nAND  d.measurement_time = (SELECT MAX(d2.measurement_time) FROM demo.climate_data d2 WHERE $__timeFilter(\"measurement_time\"))\nGROUP BY measurement_time;\n"
    }
   ]
  },
  {
   "title": "Temperature, Pressure and Windspeed at end of measurement period",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Temperature",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "docs",
     "rawSql": "SELECT\n  measurement_time as time,\n  latitude(d.geo_location) as latitude,\n  longitude(d.geo_location) as longitude,\n  latitude(d.geo_location) as latitude_raw,\n  longitude(d.geo_location) as longitude_raw,\n  data['temperature'] -273.15 as temperature,\n  gp.nearest_town\nFROM\n  demo.climate_data d\n      ,  \"demo\".\"german_regions\" r\n      , demo.geo_points gp\nWHERE WITHIN(d.geo_location, r.geo_coords)\nAND gp.geo_location = d.geo_location\nAND (r.region_name = '${region}' OR 'ALL' =  '${region}')\nAND  d.measurement_time = (SELECT d2.measurement_time FROM demo.climate_data d2 WHERE $__timeFilter(\"measurement_time\") ORDER BY measurement_time DESC LIMIT 1);\n"
    },
    {
     "dataset": "docs",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 7, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "dataset": "docs",
     "rawSql": "SELECT\n  measurement_time as time,\n  latitude(d.geo_location) as latitude,\n  longitude(d.geo_location) as longitude,\n  latitude(d.geo_location) as latitude_raw,\n  longitude(d.geo_location) as longitude_raw,\n  data['pressure'] / 100 as pressure,\n  gp.nearest_town\nFROM\n  demo.climate_data  d\n      ,  \"demo\".\"german_regions\" r \n      , demo.geo_points gp\nWHERE WITHIN(d.geo_location, r.geo_coords)\nAND (r.region_name = '${region}' OR 'ALL' =  '${region}')\nAND gp.geo_location = d.geo_location\nAND  d.measurement_time = (SELECT MAX(d2.measurement_time) FROM demo.climate_data d2 WHERE $__timeFilter(\"measurement_time\"));\n"
    }
   ]
  },
  {
   "title": "Wind Speed and Direction",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 7, "x": 15, "y": 16 },
   "targets": [
    {
     "dataset": "docs",
     "rawSql": "SELECT\n  measurement_time as time,\n  latitude(d.geo_location) as latitude,\n  longitude(d.geo_location) as longitude,\n  latitude(d.geo_location) as latitude_raw,\n  longitude(d.geo_location) as longitude_raw,\n  data['temperature'] -273.15 as temperature,\n  data['pressure'] /  100 as pressure,\n  MOD(\n        ATAN2(-data['u10'], -data['v10']) * 180.0 / PI() + 360,\n        360\n    ) AS wind_direction_deg,\n      sqrt(data['u10']*data['u10'] + data['v10']*data['v10']) AS wind_speed,\n  gp.nearest_town\nFROM\n  demo.climate_data d\n      ,  \"demo\".\"german_regions\" r\n       , demo.geo_points gp\nWHERE WITHIN(d.geo_location, r.geo_coords)\nAND (r.region_name = '${region}' OR 'ALL' =  '${region}')\nAND gp.geo_location = d.geo_location\nAND  d.measurement_time = (SELECT MAX(d2.measurement_time) FROM demo.climate_data d2 WHERE $__timeFilter(\"measurement_time\"));\n"
    }
   ]
  },
  { "title": "Change over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Min, Average and Max temperature for $region",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  measurement_time as time,\n  avg(data['temperature']) -273.15 as temperature_avg,\n  min(data['temperature']) -273.15 as temperature_min,\n  max(data['temperature']) -273.15 as temperature_max\nFROM\n  demo.climate_data d\n      ,  \"demo\".\"german_regions\" r\nWHERE WITHIN(d.geo_location, r.geo_coords)\nAND (r.region_name = '${region}' OR 'ALL' =  '${region}')\nAND $__timeFilter(\"measurement_time\")\nGROUP BY measurement_time\nORDER BY measurement_time;\n"
    }
   ]
  },
  {
   "title": "Min, Average and Max air pressure for $region",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  measurement_time as time,\n  avg(data['pressure']) / 100 as pressure_avg,\n  min(data['pressure']) / 100 as pressure_min,\n  max(data['pressure']) / 100  as pressure_max\nFROM\n  demo.climate_data d\n      ,  \"demo\".\"german_regions\" r\nWHERE WITHIN(d.geo_location, r.geo_coords)\nAND (r.region_name = '${region}' OR 'ALL' =  '${region}')\nAND $__timeFilter(\"measurement_time\")\nAND data['pressure'] IS NOT NULL\nGROUP BY measurement_time\nORDER BY measurement_time;\n"
    }
   ]
  },
  {
   "title": "Min, Average and Max wind speed for $region",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  measurement_time as time,\n  avg(sqrt(data['u10']*data['u10'] + data['v10']*data['v10'])) AS wind_speed_avg,\n  min(sqrt(data['u10']*data['u10'] + data['v10']*data['v10'])) AS wind_speed_min,\n  max(sqrt(data['u10']*data['u10'] + data['v10']*data['v10'])) AS wind_speed_max\nFROM\n  demo.climate_data d\n      ,  \"demo\".\"german_regions\" r\nWHERE WITHIN(d.geo_location, r.geo_coords)\nAND (r.region_name = '${region}' OR 'ALL' =  '${region}')\nAND $__timeFilter(\"measurement_time\")\nAND data['pressure'] IS NOT NULL\nGROUP BY measurement_time\nORDER BY measurement_time;\n"
    }
   ]
  },
  {
   "title": "Conditions at ${town_name}, ${latitude}N , ${longitude}E",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Daily average temperature for  ${town_name}, ${latitude}, ${longitude}",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  measurement_time as time,\n  avg(data['temperature']) -273.15 as temperature_avg\n  ,gp.nearest_town\nFROM\n  demo.climate_data d\n, demo.geo_points gp\nWHERE  latitude(d.geo_location) = $latitude\nAND longitude(d.geo_location)=  $longitude\nAND gp.geo_location = d.geo_location\nAND  $__timeFilter(\"measurement_time\")\nGROUP BY measurement_time,gp.nearest_town;\n"
    }
   ]
  },
  {
   "title": "Daily average air pressure for  ${town_name}, ${latitude}, ${longitude}",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  measurement_time as time,\n  avg(data['pressure']) / 100 as pressure_avg,\n  gp.nearest_town\nFROM\n  demo.climate_data d\n  , demo.geo_points gp\nWHERE $__timeFilter(\"measurement_time\")\nAND latitude(d.geo_location) = $latitude\nAND longitude(d.geo_location)=  $longitude\nAND gp.geo_location = d.geo_location\nGROUP BY measurement_time,gp.nearest_town;\n"
    }
   ]
  },
  {
   "title": "Daily average wind speed for  ${town_name}, ${latitude}, ${longitude}",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  measurement_time as time,\n  avg(sqrt(data['u10']*data['u10'] + data['v10']*data['v10'])) AS wind_speed_avg\nFROM\n  demo.climate_data d,\n  demo.geo_points gp\nWHERE $__timeFilter(\"measurement_time\")\nAND latitude(d.geo_location) = $latitude \nAND longitude(d.geo_location)=  $longitude\nAND gp.geo_location = d.geo_location\nGROUP BY measurement_time,gp.nearest_town;\n"
    }
   ]
  }
 ]
}