# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: climate_data.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'climate_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63limate_data.proto\x12\x10\x64\x65mo.stream_load\"\xf9\x01\n\x0b\x43limateData\x12\x18\n\x10measurement_time\x18\x01 \x01(\t\x12\x14\n\x0cgeo_location\x18\x02 \x03(\x01\x12>\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x30.demo.stream_load.ClimateData.ClimateMeasurement\x1az\n\x12\x43limateMeasurement\x12\x13\n\x0btemperature\x18\x01 \x01(\x01\x12\x10\n\x08pressure\x18\x02 \x01(\x01\x12\x0b\n\x03v10\x18\x03 \x01(\x01\x12\x0b\n\x03u10\x18\x04 \x01(\x01\x12\x10\n\x08latitude\x18\x05 \x01(\x01\x12\x11\n\tlongitude\x18\x06 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'climate_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIMATEDATA']._serialized_start=41
  _globals['_CLIMATEDATA']._serialized_end=290
  _globals['_CLIMATEDATA_CLIMATEMEASUREMENT']._serialized_start=168
  _globals['_CLIMATEDATA_CLIMATEMEASUREMENT']._serialized_end=290
# @@protoc_insertion_point(module_scope)
